<h1>🍒🍒library in python🍒🍒</h1>
-NumPy
-Pandas
-MatPlotib
-Seaborn
-Plotly
-SciPy


#NumPy:  Numeric Python....
-Package for scientific computing in pythn.
-NumPy s Library that provides n-dimensional array objects.
-Fast operation of arrays including logical,shape manipulating,sorting,selecting,discrete mathematics,fourier Transforms,Basic linear algebra,stastical  operation,randoom simulation and many more.

In [2]:
#1.Defining one dimensional array 
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
# to enter element of different type in array:
import numpy as np
b=np.array([1,2,3.5,'rohit','shreya',74.56,9])
print(b)
print(type(b))
print(a.dtype)
print(b.dtype)

['1' '2' '3.5' 'rohit' 'shreya' '74.56' '9']
<class 'numpy.ndarray'>
int64
<U32


<h1>☘️🍁Reshaping🍁☘️</h1>as long as the elements required for reshaping are equal in both shape.
-e.g. we can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we can not reshape it into a 3 elements 3 rows 2D array.

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
newarr=arr.reshape(3,3)
print(newarr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<h1>🐥RESIZING:🐥</h1>
-🍁the resize() function is used to create a new array with the specified shape.
-🍁 if the new array is larger than the original array,than the new array is filled with repeated copies of a. 

In [14]:
import numpy as np
a= np.array([[1,2],[3,4]])
np.resize (a,(3,2))

array([[1, 2],
       [3, 4],
       [1, 2]])

#difference bw reshape and resise
reshape does not change the original array  but only returns the changed array 
whereas the resize method returns nothing and directly changes the original array.

In [18]:
import numpy as npy
cs=np.array([1,2,3,4,5,6])
print("original array")
print(cs)
print("Changed array:")
print(cs.reshape(2,3))
print("Changed array:")
print(cs.resize(2,3))
print("original array")
print(cs)



original array
[1 2 3 4 5 6]
Changed array:
[[1 2 3]
 [4 5 6]]
Changed array:
None
original array
[[1 2 3]
 [4 5 6]]


In [24]:
#creting a 2D array
ar=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar)
print(type(ar))
print(ar.ndim)
print(ar[2][1])
print(ar[ :2,:2])
print(ar[ : :-1, : :-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
2
8
[[1 2]
 [4 5]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


Atrributes in numpy:
* ndim: provides dimensions in array
* size: numbers of elements in array
* shape: provide order of matrix
* nbytes: no. of bytes occupied by an array
* itemsize: bytes occupied by each elements of the matrix
* dtype: give types of elements

In [26]:
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)
print(a.size)
print(b.size)
print(a.shape)
print(b.shape)



[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
6
9
(6,)
(3, 3)


In [34]:
#Usual matrix:
import numpy as np
a=np.zeros ((2,4),dtype='int16')
b=np.ones ((3,4))
print(a)
print(b)
x=np.full((3,4),10)
print(x)
y=np.full((3,3),np.nan)
print(y)


[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
[[nan nan nan]
 [nan nan nan]
 [nan nan nan]]


In [36]:
import numpy as np
a=np.zeros ((2,4),dtype='int16')
b=np.ones ((3,4))
print(a)
print(b)

m=np.diag([10,20,30,40,50])
print(m)
e=np.eye(5)
print(e)


[[0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


🌺Flatten: it creates 1D array from any nD array. flatten is slow.
🌺Ravel:it creates 1D array any nD array. ravel is fast.


In [39]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=a.ravel()
print(b)
c=a.flatten()
print(c)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [40]:
d=np.random.rand(3,4)
print(d)

[[0.40388556 0.80001567 0.71341763 0.35831201]
 [0.28829955 0.2943505  0.54930268 0.34680868]
 [0.56244062 0.526714   0.87236694 0.94745067]]


In [45]:
d=np.random.randint(-4,10,size=(2,3))
print(d)

[[ 7  9 -2]
 [ 4 -2  5]]


In [46]:
d=np.arange(10,30)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [50]:
d=np.array([1,2,3,4,5,90])
print(np.sin(d))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427  0.89399666]


In [67]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,5,3],[4,5,6],[7,6,9]])
A=a.transpose()
print(A)
a.transpose()
print(np.trace(a))
print(a+b)
print(a.dot(b))
print(a@b)
print(np.matmul(a,b))
print(np.linalg.det(a))
print(np.linalg.det(b))
print(np.linalg.inv(b))
#print(np.linalg.inv(b))


[[1 4 7]
 [2 5 8]
 [3 6 9]]
15
[[ 2  7  6]
 [ 8 10 12]
 [14 14 18]]
[[ 30  33  42]
 [ 66  81  96]
 [102 129 150]]
[[ 30  33  42]
 [ 66  81  96]
 [102 129 150]]
[[ 30  33  42]
 [ 66  81  96]
 [102 129 150]]
0.0
6.000000000000025
[[ 1.5        -4.5         2.5       ]
 [ 1.         -2.          1.        ]
 [-1.83333333  4.83333333 -2.5       ]]
